pub mod assessment;
pub mod chat;
pub mod config;
pub mod courses;
pub mod db;
pub mod document_processing;
pub mod documents;
pub mod embedding;
pub mod error;
pub mod frontend;
pub mod ingestion;
pub mod llm;
pub mod models;
pub mod state;
pub mod storage;
pub mod videos;
pub mod whisper;

pub use error::{AppError, AppResult};
pub use state::AppState;
